"""
HTML generation for TechForge briefings (responsive)
"""
from datetime import datetime
from pathlib import Path


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TechForge Briefing — {date}</title>
    <style>
        :root {{
            --bg: #0f0f0f;
            --text: #e5e5e5;
            --accent: #3b82f6;
            --secondary: #1a1a1a;
        }}
        
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.6;
            padding: 20px;
        }}
        
        .container {{
            max-width: 780px;
            margin: 0 auto;
        }}
        
        header {{
            margin-bottom: 40px;
            padding-bottom: 20px;
            border-bottom: 1px solid #333;
        }}
        
        h1 {{
            font-size: 1.8rem;
            font-weight: 600;
            margin-bottom: 8px;
        }}
        
        .date {{
            color: #888;
            font-size: 0.95rem;
        }}
        
        h2 {{
            font-size: 1.35rem;
            margin: 40px 0 16px;
            color: #fff;
        }}
        
        .section {{
            margin-bottom: 32px;
        }}
        
        .signal {{
            background: var(--secondary);
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 16px;
        }}
        
        .signal h3 {{
            font-size: 1.1rem;
            margin-bottom: 12px;
            color: #fff;
        }}
        
        .signal p {{
            margin-bottom: 10px;
        }}
        
        .implications {{
            font-style: italic;
            color: #aaa;
            border-left: 3px solid var(--accent);
            padding-left: 14px;
            margin: 12px 0;
        }}
        
        .sources {{
            font-size: 0.85rem;
            color: #777;
            margin-top: 8px;
        }}
        
        footer {{
            margin-top: 60px;
            padding-top: 20px;
            border-top: 1px solid #333;
            font-size: 0.85rem;
            color: #666;
        }}
        
        @media (max-width: 600px) {{
            body {{
                padding: 16px;
            }}
            
            h1 {{
                font-size: 1.5rem;
            }}
            
            .signal {{
                padding: 16px;
            }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>TechForge Briefing</h1>
            <div class="date">{date}</div>
        </header>
        
        <div class="content">
            {content}
        </div>
        
        <footer>
            Generated by TechForge • {date}
        </footer>
    </div>
</body>
</html>
"""


def generate_html(briefing_markdown: str, date_str: str) -> str:
    """Convert briefing into responsive HTML."""
    html_content = briefing_markdown
    
    # Basic markdown conversion
    html_content = html_content.replace("## ", "<h2>").replace("\n\n", "</h2>\n\n")
    
    import re
    html_content = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html_content)
    html_content = html_content.replace("\n\n", "</p><p>")
    html_content = "<p>" + html_content + "</p>"
    
    return HTML_TEMPLATE.format(date=date_str, content=html_content)


def save_html(html_content: str, date_str: str) -> Path:
    """Save HTML to both artifacts/ and docs/ (for GitHub Pages)."""
    # Main artifacts folder
    artifacts_dir = Path("artifacts/tech-digests")
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    (artifacts_dir / f"{date_str}.html").write_text(html_content)
    
    # docs/ folder for GitHub Pages
    docs_dir = Path("docs")
    docs_dir.mkdir(exist_ok=True)
    (docs_dir / f"{date_str}.html").write_text(html_content)
    
    print(f"[HTML] Saved to artifacts/ and docs/")
    return docs_dir / f"{date_str}.html"
