"""
HTML generation for TechForge briefings (responsive, clean structure)
"""
from __future__ import annotations

import re
from pathlib import Path


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TechForge Briefing — {date}</title>
    <style>
        :root {{
            --bg: #0f0f0f;
            --text: #e5e5e5;
            --muted: #9ca3af;
            --accent: #3b82f6;
            --secondary: #161616;
            --border: #2a2a2a;
        }}

        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}

        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.65;
            padding: 28px 20px 48px;
        }}

        .container {{
            max-width: 780px;
            margin: 0 auto;
        }}

        header {{
            margin-bottom: 36px;
            padding-bottom: 20px;
            border-bottom: 1px solid var(--border);
        }}

        h1 {{
            font-size: 1.9rem;
            font-weight: 650;
            letter-spacing: -0.02em;
            margin-bottom: 8px;
        }}

        .date {{
            color: var(--muted);
            font-size: 0.95rem;
        }}

        h2 {{
            font-size: 1.25rem;
            margin: 36px 0 14px;
            color: #fff;
            letter-spacing: -0.01em;
        }}

        section {{
            margin-bottom: 28px;
        }}

        p {{
            margin: 0 0 14px;
            color: var(--text);
        }}

        .signal {{
            background: var(--secondary);
            border: 1px solid var(--border);
            padding: 18px 18px 16px;
            border-radius: 10px;
            margin-bottom: 14px;
        }}

        .signal h3 {{
            font-size: 1.05rem;
            margin-bottom: 12px;
            color: #fff;
            font-weight: 600;
            line-height: 1.35;
        }}

        .signal ul {{
            list-style: none;
            margin: 0;
            padding: 0;
            display: grid;
            gap: 10px;
        }}

        .signal li {{
            color: #d4d4d4;
        }}

        .signal li strong {{
            color: #fff;
            font-weight: 600;
        }}

        .implications {{
            font-style: italic;
            color: #b7b7b7;
            border-left: 3px solid var(--accent);
            padding: 8px 0 8px 14px;
            margin: 4px 0;
        }}

        .sources {{
            font-size: 0.85rem;
            color: #777;
            margin-top: 12px;
        }}

        .plain-list {{
            list-style: disc;
            padding-left: 1.25rem;
            display: grid;
            gap: 10px;
            color: #d4d4d4;
        }}

        .plain-list li {{
            padding-left: 0.15rem;
        }}

        footer {{
            margin-top: 56px;
            padding-top: 18px;
            border-top: 1px solid var(--border);
            font-size: 0.85rem;
            color: #666;
        }}

        @media (max-width: 600px) {{
            body {{
                padding: 18px 14px 36px;
            }}

            h1 {{
                font-size: 1.55rem;
            }}

            .signal {{
                padding: 16px;
            }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>TechForge Briefing</h1>
            <div class="date">{date}</div>
        </header>

        <div class="content">
{content}
        </div>

        <footer>
            Generated by TechForge • {date}
        </footer>
    </div>
</body>
</html>
"""


def _inline(text: str) -> str:
    """Convert bold/italic markdown and escape basic HTML."""
    text = text.replace("&", "&").replace("<", "<").replace(">", ">")
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)", r"<em>\1</em>", text)
    return text


def _split_sections(markdown: str) -> list[tuple[str, str]]:
    """Split markdown into (heading, body) pairs."""
    lines = markdown.strip().splitlines()
    sections: list[tuple[str, str]] = []
    current_heading = ""
    current_body: list[str] = []

    for line in lines:
        if line.startswith("# ") and not line.startswith("## "):
            # Document title is handled by the page template.
            continue
        if line.startswith("## "):
            if current_heading or current_body:
                sections.append((current_heading, "\n".join(current_body).strip()))
            current_heading = line[3:].strip()
            current_body = []
        else:
            current_body.append(line)

    if current_heading or current_body:
        sections.append((current_heading, "\n".join(current_body).strip()))

    return sections


def _parse_signals(body: str) -> list[dict]:
    """Parse Top Signals nested bullets into structured cards."""
    signals: list[dict] = []
    current: dict | None = None

    for raw in body.splitlines():
        line = raw.rstrip()
        if not line.strip():
            continue

        top = re.match(r"^-\s+\*\*(.+?)\*\*\s*$", line)
        if top:
            if current:
                signals.append(current)
            current = {"title": top.group(1).strip(), "bullets": [], "sources": ""}
            continue

        if current is None:
            continue

        nested = re.match(r"^\s{2,}-\s+(.*)$", line)
        if nested:
            current["bullets"].append(nested.group(1).strip())
            continue

        sources = re.match(r"^\s*\(Sources?:\s*(.+?)\)\s*$", line, re.IGNORECASE)
        if sources:
            current["sources"] = sources.group(1).strip()
            continue

        if line.strip().startswith("(") and "source" in line.lower():
            current["sources"] = line.strip().strip("()")
        elif line.strip():
            current["bullets"].append(line.strip())

    if current:
        signals.append(current)
    return signals


def _render_signal_card(signal: dict) -> str:
    items: list[str] = []
    for bullet in signal.get("bullets", []):
        if ":" in bullet and not bullet.lower().startswith("http"):
            label, value = bullet.split(":", 1)
            label = label.strip()
            value = value.strip()
            if label.lower().startswith("implications"):
                items.append(
                    f'                <li class="implications"><strong>{_inline(label)}:</strong> {_inline(value)}</li>'
                )
            else:
                items.append(
                    f"                <li><strong>{_inline(label)}:</strong> {_inline(value)}</li>"
                )
        else:
            items.append(f"                <li>{_inline(bullet)}</li>")

    sources_html = ""
    if signal.get("sources"):
        sources_html = (
            f'\n            <div class="sources">Sources: {_inline(signal["sources"])}</div>'
        )

    bullets_html = "\n".join(items) if items else "                <li></li>"
    return (
        f'        <article class="signal">\n'
        f'            <h3>{_inline(signal["title"])}</h3>\n'
        f"            <ul>\n{bullets_html}\n            </ul>{sources_html}\n"
        f"        </article>"
    )


def _render_plain_list(body: str) -> str:
    items: list[str] = []
    for raw in body.splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("- "):
            items.append(f"            <li>{_inline(line[2:].strip())}</li>")
        else:
            items.append(f"            <li>{_inline(line)}</li>")
    if not items:
        return f"        <p>{_inline(body)}</p>"
    return '        <ul class="plain-list">\n' + "\n".join(items) + "\n        </ul>"


def _render_paragraphs(body: str) -> str:
    chunks = [c.strip() for c in re.split(r"\n\s*\n", body) if c.strip()]
    if not chunks:
        return ""
    return "\n".join(
        f"        <p>{_inline(chunk.replace(chr(10), ' '))}</p>" for chunk in chunks
    )


def markdown_to_html(briefing_markdown: str) -> str:
    """Convert TechForge briefing markdown into clean semantic HTML."""
    parts: list[str] = []

    for heading, body in _split_sections(briefing_markdown):
        if not heading and not body:
            continue

        section_bits: list[str] = ["        <section>"]
        if heading:
            section_bits.append(f"        <h2>{_inline(heading)}</h2>")

        heading_l = heading.lower()
        if "top signals" in heading_l:
            signals = _parse_signals(body)
            if signals:
                section_bits.extend(_render_signal_card(s) for s in signals)
            else:
                section_bits.append(_render_paragraphs(body))
        elif "what to watch" in heading_l or any(
            line.strip().startswith("- ") for line in body.splitlines()
        ):
            if any(line.strip().startswith("- ") for line in body.splitlines()):
                section_bits.append(_render_plain_list(body))
            else:
                section_bits.append(_render_paragraphs(body))
        else:
            section_bits.append(_render_paragraphs(body))

        section_bits.append("        </section>")
        parts.append("\n".join(section_bits))

    return "\n\n".join(parts)


def generate_html(briefing_markdown: str, date_str: str) -> str:
    """Convert briefing into responsive HTML."""
    content = markdown_to_html(briefing_markdown)
    return HTML_TEMPLATE.format(date=date_str, content=content)


def save_html(html_content: str, date_str: str) -> Path:
    """Save HTML to artifacts/ (and docs/ for GitHub Pages compatibility)."""
    artifacts_dir = Path("artifacts/tech-digests")
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    artifact_path = artifacts_dir / f"{date_str}.html"
    artifact_path.write_text(html_content)

    docs_dir = Path("docs")
    docs_dir.mkdir(exist_ok=True)
    (docs_dir / f"{date_str}.html").write_text(html_content)

    print("[HTML] Saved to artifacts/ and docs/")
    return artifact_path
